name: CD

on: 
  workflow_run:
    workflows: [CI]
    types:
    - completed

jobs:
  CD:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - uses: actions/checkout@v4